


- id: 10.1121/10.0036887
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_Brosseau_etal_JASA.jpg
  buttons:
    - type: pdf
      link: pdfs/2025_Fradet_etal_JASA.pdf
  tags:
    - monitoring
    - acoustics





- id: doi:10.32942/X2Z056
  image: https://quantmarineecolab.github.io/images/journal_covers/ecoevorxiv.jpg
  buttons:
    - type: pdf
      link: pdfs/2025_Spiecker_etal_EcoEvoRxiv.pdf
  tags:
    - monitoring
    - estuaries



- id: doi:10.1002/ecs2.70193
  image: https://quantmarineecolab.github.io/images/journal_covers/2025_ZarcoPerello_etal_Ecosphere.jpg
  buttons:
    - type: pdf
      link: pdfs/2025_ZarcoPerello_etal_Ecosphere.pdf
  tags:
    - coral reefs
    - biodiversity




- id: doi:10.1111/csp2.13249
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_ConSciPrac.jpg
  buttons:
    - type: pdf
      link: pdfs/2024_Saltzman_etal_ConSciPrac.pdf
  tags:
    - marine megafauna
    - turtles




- id: doi:10.1007/s12080-024-00594-4
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_WulfingWhite_TheoEco.png
  buttons:
    - type: pdf
      link: pdfs/2024_WulfingWhite_TheoEco.pdf
    - type: source
      link: https://github.com/swulfing/SocEco
      text: Code
  tags:
    - socio-ecological 
    - mathematical model






- id: doi:10.1121/10.0028204
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_Brosseau_etal_JASA.jpg
  buttons:
    - type: pdf
      link: pdfs/2024_Brosseau_etal_JASA.pdf
  tags:
    - disturbance
    - acoustics
    - seabirds






- id: doi:10.1093/jmammal/gyae083
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_Smith_etal_Mammology.jpeg
  buttons:
    - type: pdf
      link: pdfs/2024_Smith_etal_Mammology.pdf
  tags:
    - pikas
    - spatial ecology
    - climate change





- id: doi:10.7717/peerj.17832
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_PeerJ.png
  buttons:
    - type: pdf
      link: pdfs/2024_Fairchild_etal_PeerJ.pdf
    - type: source
      link: https://github.com/swulfing/TeamLump
      text: Code
    - type: preprint
      link: https://doi.org/10.32942/X25P7Q
      text: Preprint
  tags:
    - aquaculture
    - fisheries
    - climate change

- id: doi:10.3390/su16146078
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_BakerMedard_etal_Sustainability.jpg
  buttons:
    - type: pdf
      link: pdfs/2024_BakerMedard_etal_Sustainability.pdf
  tags:
    - socio-ecological
    - marine conservation
    - fisheries







- id: doi:10.1016/j.ecolmodel.2024.110786
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_WhiteWulfing_EcoMod.png
  buttons:
    - type: pdf
      link: pdfs/2024_WhiteWulfing_EcoMod.pdf
    - type: source
      link: https://github.com/QuantMarineEcoLab/socio-eco-shocks
      text: Code
    - type: preprint
      link: https://doi.org/10.32942/X29G7W
      text: Preprint
  tags:
    - socio-ecological
    - mechanistic model
    - extreme events
    - heatwaves





- id: doi:10.1111/1365-2656.14120
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_VilleneuveWhite_JAnimEco.jpg
  buttons:
    - type: pdf
      link: pdfs/2024_VilleneuveWhite_JAnimEco.pdf
    - type: source
      link: https://doi.org/10.5061/dryad.8w9ghx3tx
      text: Code
    - type: preprint
      link: https://ecoevorxiv.org/repository/view/6604/
      text: Preprint
    - type: blog 
      link: https://animalecologyinfocus.com/2024/06/12/an-organismal-crystal-ball-during-marine-heatwaves-predicting-death-across-heat-doses/
  tags:
    - shellfish
    - climate change
    - mechanistic model
    - extreme events
    - heatwaves




- id: doi:10.1016/j.fishres.2024.107045
  image: https://quantmarineecolab.github.io/images/journal_covers/2024_Wulfing_etal_FishRes.jpg
  buttons:
    - type: pdf
      link: pdfs/2024_Wulfing_etal_FishRes.pdf
    - type: source
      link: https://github.com/swulfing/OCyanea
      text: Code
  tags:
    - fisheries
    - Madagascar
    - mathematical model








- id: doi:10.1186/s44263-023-00028-z
  image: https://quantmarineecolab.github.io/images/journal_covers/2023_Althouse_etal_BMC.jpg
  buttons:
    - type: pdf
      link: pdfs/2023_Althouse_etal_BMC.pdf
    - type: source
      link: https://github.com/LaurentHebert/cloSIR
      text: Code
  tags:
    - COVID-19
    - infectious diseases










- id: doi:10.32942/X2CC97
  image: https://quantmarineecolab.github.io/images/journal_covers/ecoevorxiv.jpg
  buttons:
    - type: pdf
      link: pdfs/2023_Zarco-Perello_etal_ecoevorxiv.pdf
  tags:
    - ecological networks
    - monitoring







- id: doi:10.32942/X2J60N
  image: https://quantmarineecolab.github.io/images/journal_covers/ecoevorxiv.jpg
  buttons:
    - type: pdf
      link: pdfs/2023_Whiteetal_ecoevorxiv.pdf
  tags:
    - sharks and rays
    - fisheries
    - seafood




- id: doi:10.3354/meps14435
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Kessel_etal_MEPS.png
  buttons:
    - type: pdf
      link: pdfs/2023_SaltzmanWhite_MEPS.pdf
    - type: blog 
      link: https://www.forbes.com/sites/melissacristinamarquez/2023/12/01/unveiling-the-secrets-of-planktivorous-sharks
  tags:
    - sharks and rays
    - species trends





- id: doi:10.1093/biosci/biad015
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_White_Bioscience.png
  buttons:
    - type: pdf
      link: pdfs/2023_Cuddington_etal_BioScience.pdf
    - type: blog 
      link: https://www.unh.edu/unhtoday/2023/05/quantitative-confidence
  tags:
    - biology education
    - mathematical biology


- id: doi:10.1139/facets-2022-0079
  image: https://quantmarineecolab.github.io/images/journal_covers/2023_Heard_etal_Facets.jpg
  buttons:
    - type: pdf
      link: pdfs/2023_Heard_etal_Facets.pdf
  tags:
    - science communication
    - ecology





- id: doi:10.3389/fcosc.2022.987909
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Stoll_et_al_FrontSustFood.png
  buttons:
    - type: pdf
      link: pdfs/2022_Saltzman_etal_FronConSci.pdf
  tags:
    - marine social science
    - sawfish
    - research methods






- id: doi:10.1007/s10980-022-01473-1
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_Beasley_etal_LandEco.jpg
  buttons:
    - type: pdf
      link: pdfs/2022_Beasley_etal_LandEco.pdf
  tags:
    - coffee
    - spatial ecology
    - disease





- id: doi:10.1016/j.marpol.2022.105054
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_WardPaige_etal_MarPol.png
  buttons:
    - type: pdf
      link: pdfs/2022_WardPaige_etal_MarPol.pdf
  tags:
    - COVID-19
    - novel data streams
    - socio-ecological




- id: doi:10.7717/peerj.13007
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_PeerJ.png
  buttons:
    - type: pdf
      link: pdfs/2022_White_etal_PeerJ.pdf
    - type: blog 
      link: https://www.unh.edu/unhtoday/news/release/2022/03/21/unh-research-us-seafood-workers-increased-risk-covid-19-during-pandemic
  tags:
    - COVID-19
    - novel data streams
    - fisheries
    - seafood
    - worker safety



- id: doi:10.1111/csp2.611
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_ConSciPrac.jpg
  buttons:
    - type: pdf
      link: pdfs/2022_White_etal_ConSciPrac.pdf
  tags:
    - conservation
    - monitoring
    - time series
    - marine mammals



- id: doi:10.1016/j.ocecoaman.2021.105925
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_OCM.jpg
  buttons:
    - type: pdf
      link: pdfs/2022_White_etal_OCM.pdf
    - type: source
      link: https://github.com/eastonwhite/GFW-Madagascar
      text: Code
    - type: blog 
      link: https://quantmarineecolab.github.io/2021/12/15/madagascar-distant-fishing-paper.html
  tags:
    - Madagascar
    - novel data streams
    - fisheries
    - marine protected areas

    
    
    
    
- id: doi:10.1016/j.envsci.2021.06.007
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_BakerMedard_etal_EnvSciPol.jpg
  buttons:
    - type: pdf
      link: pdfs/2021_BakerMedard_etal_EnvSciPol.pdf
  tags:
    - socio-ecological
    - marine protected areas
    - Madagascar
    - conservation




- id: doi:10.1111/1365-2656.13560
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Osgood_et_al_AnimalEco.jpg
  buttons:
    - type: pdf
      link: pdfs/2021_Osgood_et_al_AnimalEco.pdf
    - type: github
      link: baumlab/Osgood_etal_2021_JAE
  tags:
    - monitoring
    - sharks and rays
    - climate change




- id: doi:10.1016/j.ecoinf.2021.101336
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Bahlai_etal_EcoInformatics.jpg
  buttons:
    - type: pdf
      link: pdfs/2021_Bahlai_etal_EcoInformatics.pdf
  tags:
    - monitoring
    - time series



- id: doi:10.3389/fsufs.2021.614368
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Stoll_et_al_FrontSustFood.png
  buttons:
    - type: pdf
      link: pdfs/2021_Stoll_et_al_FrontSustFood.pdf
  tags:
    - COVID-19
    - seafood
    - fisheries




- id: doi:10.1111/oik.07770
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_White_etal_Oikos.png
  buttons:
    - type: pdf
      link: pdfs/2020_White_etal_Oikos.pdf
    - type: source
      link: https://github.com/eastonwhite/MPA-disturbances
      text: Code
  tags:
    - monitoring
    - marine protected areas
    - fisheries
    - spatial ecology


- id: doi:10.1016/j.marpol.2020.104328
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_Froehlich_etal_MarPol.png
  buttons:
    - type: pdf
      link: pdfs/2020_Froehlich_etal_MarPol.pdf
  tags:
    - COVID-19
    - seafood
    - fisheries




- id: doi:10.1111/faf.12525
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_White_etal_FishFisheries.png
  buttons:
    - type: pdf
      link: pdfs/2020_White_etal_FishFisheries.pdf
    - type: github
      link: eastonwhite/COVID19_US_Fisheries
    - type: blog 
      link: https://quantmarineecolab.github.io/2020/11/15/seafood-and-covid-paper.html
  tags:
    - monitoring
    - COVID-19
    - seafood
    - fisheries



- id: doi:10.1016/j.ecolind.2020.107096
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_BruelWhite_EcoInd.png
  buttons:
    - type: pdf
      link: pdfs/2020_BruelWhite_EcoInd.pdf
    - type: source
      link: https://github.com/rosalieb/temporal-sampling
      text: Code
  tags:
    - monitoring
    - population model
    - conservation



- id: doi:10.3389/fevo.2020.572979
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_WhiteBahlai_FronEcoEvo.png
  buttons:
    - type: pdf
      link: pdfs/2020_WhiteBahlai_FronEcoEvo.pdf
  tags:
    - monitoring
    - population model
    - conservation




- id: doi:10.1371/journal.pone.0240648
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_WhiteHerbert-Dufresne_PLoSOne.png
  buttons:
    - type: pdf
      link: pdfs/2020_WhiteHerbert-Dufresne_PLoSOne.pdf
    - type: source
      link: https://github.com/eastonwhite/COVID19_US_States
      text: Code
  tags:
    - COVID-19
    - public health




- id: doi:10.1016/j.ecocom.2020.100867
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_WhiteHastings_EcoComp.png
  buttons:
    - type: pdf
      link: pdfs/2020_WhiteHastings_EcoComp.pdf
  tags:
    - seasonality
    - population model



- id: doi:10.1073/pnas.1911440116
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_White_etal_PNAS.png
  buttons:
    - type: pdf
      link: pdfs/2019_White_etal_PNAS.pdf
    - type: source
      link: https://github.com/eastonwhite/species-management-variability
      text: Code
  tags:
    - beetles
    - monitoring
    - spatial ecology



- id: doi:10.1016/j.biocon.2019.07.011
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_Rodriquez-Caro_BioCon.png
  buttons:
    - type: pdf
      link: pdfs/2019_Rodriquez-Caro_BioCon.pdf
  tags:
    - monitoring
    - population model



- id: doi:10.1111/cobi.13371
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_Fournier_etal_ConBio.png
  buttons:
    - type: pdf
      link: pdfs/2019_Fournier_etal_ConBio.pdf
    - type: source
      link: https://github.com/aurielfournier/negative_population_trends
      text: Code
  tags:
    - monitoring
    - conservation



- id: doi:10.1093/biosci/biy144
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_White_Bioscience.png
  buttons:
    - type: pdf
      link: pdfs/2019_White_Bioscience.pdf
    - type: source
      link: https://github.com/eastonwhite/time-series-project
      text: Code
  tags:
    - monitoring
    - conservation



- id: doi:10.1002/ecy.2546
  image: https://quantmarineecolab.github.io/images/journal_covers/2018_WhiteSmith_Ecology.png
  buttons:
    - type: pdf
      link: pdfs/2018_WhiteSmith_Ecology.pdf
    - type: source
      link: https://github.com/eastonwhite/BodiePikaMetapop
      text: Code
  tags:
    - pikas
    - spatial ecology
    - conservation

      

- id: doi:10.1111/cobi.12478
  image: https://quantmarineecolab.github.io/images/journal_covers/2015_White_etal_ConBio.png
  buttons:
    - type: pdf
      link: pdfs/2015_White_etal_ConBio.pdf
    - type: source
      link: https://github.com/eastonwhite/Cocos_Models
      text: Code
  tags:
    - sharks and rays
    - marine protected areas
    - conservation



- id: doi:10.1186/1745-6150-9-23
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_White_etal_BiologyDirect.png
  buttons:
    - type: pdf
      link: pdfs/2014_White_etal_BiologyDirect.pdf
    - type: source
      link: https://github.com/eastonwhite/LemonShark_Models
      text: Code
  tags:
    - sharks and rays
    - population model
    - conservation


- id: doi:10.3354/meps10966
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Kessel_etal_MEPS.png
  buttons:
    - type: pdf
      link: pdfs/2014_Kessel_etal_MEPS.pdf
  tags:
    - sharks and rays
    - seasonality




- id: doi:10.1016/j.marpol.2014.03.012
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Robinson_etal_MarinePol.png
  buttons:
    - type: pdf
      link: pdfs/2014_Robinson_etal_MarinePol.pdf
  tags:
    - conservation
    - biodiversity




- id: doi:10.1111/1365-2664.12177
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_GerberWhite_JAppEco.png
  buttons:
    - type: pdf
      link: pdfs/2014_GerberWhite_JAppEco.pdf
  tags:
    - conservation
    - population model



- id: doi:10.1111/acv.12051
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Senko_et_al_AnimConserv.png
  buttons:
    - type: pdf
      link: pdfs/2014_Senko_et_al_AnimConserv.pdf
  tags:
    - conservation
    - fisheries
      

